POST http://localhost:3000/api/toto
Content-Type: application/json

{
    "data": {
        "name" : "Toto"
    }

}

###
GET http://localhost:3000/api/toto

### 
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "data":{
        "name": "Testeur"
    }
}

### 
GET http://localhost:3000/api/users